export const Users = [
    {
      id:1,
      profilePicture: "person/image.jpeg",
      username: "Saumya Shriavstava",
    },
    {
      id:2,
      profilePicture: "person/image2.jpeg",
      username: "Praveen maurya",
    },
    {
      id:3,
      profilePicture: "person/image3.jpeg",
      username: "Shubhum Kumar",
    },
    {
      id:4,
      profilePicture: "person/image4.avif",
      username: "Priyanshu Ranjan",
    },
    {
      id:5,
      profilePicture: "person/image5.webp",
      username: "Dipandhu kumar",
    },
    {
      id:6,
      profilePicture: "person/image6.png",
      username: "Rahul Kumar",
    },
    {
      id:7,
      profilePicture: "person/image7.jpeg",
      username: "Happy Raj",
    },
    {
      id:8,
      profilePicture: "person/image8.jpeg",
      username: "Saumya Shrivastava",
    },
    {
      id:9,
      profilePicture: "person/image9.jpg",
      username: "Adhiraj Singh",
    },
    {
      id:10,
      profilePicture: "person/image10.jpg",
      username: "Aniket Kumar",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "post/post1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "post/post2.avif",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "post/post3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "post/post4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "post/post5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "post/post6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "post/post7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "post/post8.png",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "post/post9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "post/post10.webp",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];